### ISSUE TITLE
Cannot use the tool using runas /netonly context

### ISSUE THREAD

**Issue by jaredbarez** [dev-2null/ADCollector#1]
Please add support for using the tool from within context of runas /netonly, such as e.g. `runas.exe /netonly /user:USER@DOMAIN.FQDN cmd.exe`. Thanks

**Comment by dev-2null** [comment]
Hi, Could you provide the command and output? I'm able to run the tool with `/netonly`. Probably some functions are not properly implemented.

**Comment by dev-2null** [comment]
I just found that I got an error message if I issue runas with UPN USER@DOMAIN.FQDN, but it works fine with domain\user. I'll take a look..

**Comment by dev-2null** [comment]
Hey, I would recommend you to use `Domain\User` format when you issue the `runas` command. 
There's sth wrong with the security context if you use UPN. `[System.DirectoryServices.ActiveDirectory.Domain]::GetCurrentDomain()` will return "Current security context is not associated with an Active Directory domain or forest."  Do you have any specific reason to use UPN?

**Comment by jaredbarez** [comment]
Thanks for resolving the issue. And no, I have no specific reason to use UPN.
