### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by mabangde** [dev-2null/ADCollector#3]
![image](https://user-images.githubusercontent.com/6219246/134112871-2835900f-893b-406c-a38c-d895bac367ba.png)

**Comment by dev-2null** [comment]
Hi, could you add 
```csharp
Console.WriteLine(rule.IdentityReference);
```
before 
```csharp
var sid = rule.IdentityReference.Translate(typeof(SecurityIdentifier)).ToString();
```
 in  https://github.com/dev-2null/ADCollector/blob/master/ADCollector/Utilities.cs#L1302 to check the identity reference of the target object?

And could you add a try & catch to see if you get the correct result?
```csharp
string sid = null;
try
{
    sid = rule.IdentityReference.Translate(typeof(SecurityIdentifier)).ToString();
}
catch
{
    sid = rule.IdentityReference.ToString()
}
```

Adding a try & catch should solve this issue, from my understanding, it is trying to enumerate a deleted account
```csharp
string sid = null;
try {sid =  rule.IdentityReference.Translate(typeof(SecurityIdentifier)).ToString();}
catch{continue;}
```
Could you test if it works?

**Comment by dev-2null** [comment]
I'm closing this as no feedback can be provided, hopefully v2.1.2 could fix this, let me know if you face this issue again
