### ISSUE TITLE
Connection failed, Please check if you are using a domain account.

### ISSUE THREAD

**Issue by mendacus** [dev-2null/ADCollector#4]
Hi dev-2null,

I am attempting to use this via `execute-assembly` in CobaltStrike. Albeit, I have not generated the EXE from this repo, I get an error in compilation. So, I've started using one via the SharpCollection repository.

At this time, running ADcollector via NetFramework_4.5_x64 I get the error listed in the title. It finishes checks for:

1. Current Domain / Forest
2. LDAP, Kerberos, Domain, Group Policy information
3. Discoverable DC's
4. Trust accounts, objects, and domain relationships.
5. Domains in forest
6. Trusted domain objects in the forest root
7. Forest trust relationships
8. Effective GPOs

Finally, after GPOs, it errors and results in the message in the title. I can confirm I am a domain user, as the session I live in is successfully tied to AD. I can perform simple checks like `net` and `klist` to query information in the domain.

Let me know what you think or how I can better help you. Thanks in advance.

**Comment by dev-2null** [comment]
Hey mendacus,
Could you check the version of ADCollector you were using (the most current one is 3.0.1)? The one from SharpCollection repo is probably outdated. I just downloaded my repo and compiled it without any error. Maybe you can try to build/rebuild it for a few times or switch from Debug to Release to see if it works. 
Let me know the error details if you are still not able to compile/run it successfully.

**Comment by mendacus** [comment]
Hey again, apologies for the delayed response.

Versioning = 3.0.1

Executing with "execute-assembly /path/to/ADCollector.exe --Domain mydomain.net"

![image](https://user-images.githubusercontent.com/118392221/216359099-ea5e2638-1415-4e1f-820b-bc32cf920d3c.png)

I've gone through and compiled the following:
Debug (x64 and Any CPU)
Release (x64 and Any CPU)

Attempting this again via Cobalt, I get the error posted above. It no longer reaches to the point of the last post. What else can I do to assist? It does seem to be making the connection properly, according to debug:

![image](https://user-images.githubusercontent.com/118392221/216361485-8056dd8f-9e76-44fd-8618-adf5a5dd8370.png)

**Comment by dev-2null** [comment]
I don't have a CS license atm, with the information you provided I'm not sure what really went wrong. Would it be possible for you to access the target domain directly or via proxy? I always use `runas` with `/netonly` flag on my own VM.
Maybe you can try to comment out some functions here to see if it works https://github.com/dev-2null/ADCollector/blob/master/ADCollector3/ADCollector.cs#L29

**Comment by mendacus** [comment]
Thanks for the response - I will keep playing around with it. Ideally this could be ran, like you said, through a proxy. Execute assembly was only a want, not a need. Appreciate the help along the way.

**Comment by dev-2null** [comment]
No worries, feel free to contact me if you get any other issues, I'm glad to help.
